//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungeonLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LibrarySkin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LibrarySkin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DungeonLibrary.LibrarySkin", typeof(LibrarySkin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hit {1} for {2} damage!.
        /// </summary>
        internal static string attacking {
            get {
                return ResourceManager.GetString("attacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the daylight, it&apos;s looking kind of weak!.
        /// </summary>
        internal static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonic!.
        /// </summary>
        internal static string demonic {
            get {
                return ResourceManager.GetString("demonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: {6}.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s a flood of them!.
        /// </summary>
        internal static string flood {
            get {
                return ResourceManager.GetString("flood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluffy!.
        /// </summary>
        internal static string fluffy {
            get {
                return ResourceManager.GetString("fluffy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Black Gorilla.
        /// </summary>
        internal static string g1 {
            get {
                return ResourceManager.GetString("g1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uhhh ohhhh, a gorilla..
        /// </summary>
        internal static string g1description {
            get {
                return ResourceManager.GetString("g1description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block: +{3}.
        /// </summary>
        internal static string itemblock {
            get {
                return ResourceManager.GetString("itemblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage: +{1}.
        /// </summary>
        internal static string itemdamage {
            get {
                return ResourceManager.GetString("itemdamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Hit: +{2}%.
        /// </summary>
        internal static string itemhit {
            get {
                return ResourceManager.GetString("itemhit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rarity: {4}.
        /// </summary>
        internal static string itemrarity {
            get {
                return ResourceManager.GetString("itemrarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} missed!.
        /// </summary>
        internal static string missed {
            get {
                return ResourceManager.GetString("missed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under the moonlight, it looks quite angry and strong....
        /// </summary>
        internal static string night {
            get {
                return ResourceManager.GetString("night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string notDemonic {
            get {
                return ResourceManager.GetString("notDemonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s only one of them.
        /// </summary>
        internal static string notFlood {
            get {
                return ResourceManager.GetString("notFlood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not fluffy.
        /// </summary>
        internal static string notFluffy {
            get {
                return ResourceManager.GetString("notFluffy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-Handed.
        /// </summary>
        internal static string onehand {
            get {
                return ResourceManager.GetString("onehand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life: {1}/{2}.
        /// </summary>
        internal static string ow2 {
            get {
                return ResourceManager.GetString("ow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage: {3} - {4}.
        /// </summary>
        internal static string ow3 {
            get {
                return ResourceManager.GetString("ow3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block: {5}.
        /// </summary>
        internal static string ow4 {
            get {
                return ResourceManager.GetString("ow4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:
        ///{6}.
        /// </summary>
        internal static string ow5 {
            get {
                return ResourceManager.GetString("ow5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life: {1}/{2}.
        /// </summary>
        internal static string p2 {
            get {
                return ResourceManager.GetString("p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit Chance: {3}%.
        /// </summary>
        internal static string p3 {
            get {
                return ResourceManager.GetString("p3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block: {5}.
        /// </summary>
        internal static string p4 {
            get {
                return ResourceManager.GetString("p4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon: {4}.
        /// </summary>
        internal static string p5 {
            get {
                return ResourceManager.GetString("p5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item: {7}
        ///.
        /// </summary>
        internal static string p6 {
            get {
                return ResourceManager.GetString("p6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Baby Rabbit.
        /// </summary>
        internal static string r2 {
            get {
                return ResourceManager.GetString("r2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s just a cute little bunny...Why would you want to fight it?.
        /// </summary>
        internal static string r2description {
            get {
                return ResourceManager.GetString("r2description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *****MONSTER*****.
        /// </summary>
        internal static string scarymonster {
            get {
                return ResourceManager.GetString("scarymonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-Handed.
        /// </summary>
        internal static string twohand {
            get {
                return ResourceManager.GetString("twohand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Hit: {3}%.
        /// </summary>
        internal static string wbonus {
            get {
                return ResourceManager.GetString("wbonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}-{2} Damage.
        /// </summary>
        internal static string wdamage {
            get {
                return ResourceManager.GetString("wdamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Zombie.
        /// </summary>
        internal static string z2 {
            get {
                return ResourceManager.GetString("z2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s a zombie! Don&apos;t get biten!.
        /// </summary>
        internal static string z2description {
            get {
                return ResourceManager.GetString("z2description", resourceCulture);
            }
        }
    }
}
