//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dungeon {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class skin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal skin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dungeon.skin", typeof(skin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have chosen an improper action....
        /// </summary>
        internal static string actionNO {
            get {
                return ResourceManager.GetString("actionNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack!.
        /// </summary>
        internal static string attack {
            get {
                return ResourceManager.GetString("attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruthless Caveman.
        /// </summary>
        internal static string caveman {
            get {
                return ResourceManager.GetString("caveman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The monster dropped no loot, cheap bastard....
        /// </summary>
        internal static string cheap {
            get {
                return ResourceManager.GetString("cheap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassailable Chief.
        /// </summary>
        internal static string chief {
            get {
                return ResourceManager.GetString("chief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an action:
        ///1) Attack
        ///2) Run
        ///3) Player Information
        ///4) Monster Information
        ///5) Exit Application.
        /// </summary>
        internal static string chooseAction {
            get {
                return ResourceManager.GetString("chooseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneath the monster&apos;s corpose was... {0}! You found an item!.
        /// </summary>
        internal static string corpse {
            get {
                return ResourceManager.GetString("corpse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You killed {0}!.
        /// </summary>
        internal static string d1 {
            get {
                return ResourceManager.GetString("d1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are dead!.
        /// </summary>
        internal static string dead {
            get {
                return ResourceManager.GetString("dead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The monster delivers the final blow, and as you fell to the ground, you wondered what you did wrong. Maybe you were not born a warrior afterall, or maybe attacking {0} was not as wise as you thought...But none of that matters now. You closed your eyes in remorse and entered your enternal slumber....
        /// </summary>
        internal static string death {
            get {
                return ResourceManager.GetString("death", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominating Deathwing.
        /// </summary>
        internal static string deathwing {
            get {
                return ResourceManager.GetString("deathwing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monsters Defeated: .
        /// </summary>
        internal static string defeat {
            get {
                return ResourceManager.GetString("defeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have defeated {0} monsters!
        ///(Enter any key to exit).
        /// </summary>
        internal static string defeatmonsters {
            get {
                return ResourceManager.GetString("defeatmonsters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disgraceful....
        /// </summary>
        internal static string disgrace {
            get {
                return ResourceManager.GetString("disgrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agile Elf.
        /// </summary>
        internal static string elf {
            get {
                return ResourceManager.GetString("elf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is now equipped!.
        /// </summary>
        internal static string equip {
            get {
                return ResourceManager.GetString("equip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonic Gorilla.
        /// </summary>
        internal static string g2 {
            get {
                return ResourceManager.GetString("g2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uh oh, That&apos;s a big gorilla.
        /// </summary>
        internal static string g2description {
            get {
                return ResourceManager.GetString("g2description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game over!
        ///.
        /// </summary>
        internal static string gameover {
            get {
                return ResourceManager.GetString("gameover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cute Gnome.
        /// </summary>
        internal static string gnome {
            get {
                return ResourceManager.GetString("gnome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cunning Goblin.
        /// </summary>
        internal static string goblin {
            get {
                return ResourceManager.GetString("goblin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon Tear.
        /// </summary>
        internal static string i1 {
            get {
                return ResourceManager.GetString("i1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internationalization.
        /// </summary>
        internal static string i18n {
            get {
                return ResourceManager.GetString("i18n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A blinding light shines from the corpse of the monster, devouring its body. A line of words rises to the air, you struggle to read what it says...it says &apos;Unicode is the future&apos;...?
        ///
        ///You discovered {0}!.
        /// </summary>
        internal static string i18n2 {
            get {
                return ResourceManager.GetString("i18n2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dazzling light shimmers under the monster&apos;s limp body, you discovered a legendary item, the {0}!.
        /// </summary>
        internal static string i18n3 {
            get {
                return ResourceManager.GetString("i18n3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odin&apos;s Eye.
        /// </summary>
        internal static string i2 {
            get {
                return ResourceManager.GetString("i2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blizzard Flame.
        /// </summary>
        internal static string i3 {
            get {
                return ResourceManager.GetString("i3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crown of Destruction.
        /// </summary>
        internal static string i4 {
            get {
                return ResourceManager.GetString("i4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor of the Titans.
        /// </summary>
        internal static string i5 {
            get {
                return ResourceManager.GetString("i5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Item.
        /// </summary>
        internal static string i6 {
            get {
                return ResourceManager.GetString("i6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King of Internationalization.
        /// </summary>
        internal static string i7 {
            get {
                return ResourceManager.GetString("i7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this room: {0}.
        /// </summary>
        internal static string inThisRoom {
            get {
                return ResourceManager.GetString("inThisRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You compared the item to the one you had, and discarded it. The one you had was much better..
        /// </summary>
        internal static string item {
            get {
                return ResourceManager.GetString("item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization Professional.
        /// </summary>
        internal static string localization {
            get {
                return ResourceManager.GetString("localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The monster dropped a {0}.
        /// </summary>
        internal static string loot {
            get {
                return ResourceManager.GetString("loot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} attacks you as you run!.
        /// </summary>
        internal static string monsterattack {
            get {
                return ResourceManager.GetString("monsterattack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster Information: .
        /// </summary>
        internal static string monsterinfo {
            get {
                return ResourceManager.GetString("monsterinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancient Native.
        /// </summary>
        internal static string native {
            get {
                return ResourceManager.GetString("native", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indestructible Orc.
        /// </summary>
        internal static string orc {
            get {
                return ResourceManager.GetString("orc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Potion.
        /// </summary>
        internal static string p1 {
            get {
                return ResourceManager.GetString("p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Elixir.
        /// </summary>
        internal static string p2 {
            get {
                return ResourceManager.GetString("p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison Potion.
        /// </summary>
        internal static string p3 {
            get {
                return ResourceManager.GetString("p3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandaid.
        /// </summary>
        internal static string p4 {
            get {
                return ResourceManager.GetString("p4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Poison.
        /// </summary>
        internal static string p5 {
            get {
                return ResourceManager.GetString("p5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Information: .
        /// </summary>
        internal static string playerinfo {
            get {
                return ResourceManager.GetString("playerinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison.
        /// </summary>
        internal static string poison {
            get {
                return ResourceManager.GetString("poison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foolish as you are, you drank the potion in one breath and lost {0} health...  Current health: {1}-{0}/{2}.
        /// </summary>
        internal static string potion {
            get {
                return ResourceManager.GetString("potion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You used it and gained {0} health! Current health: {1}+{0}/{2}
        ///.
        /// </summary>
        internal static string potion2 {
            get {
                return ResourceManager.GetString("potion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Furball rabit.
        /// </summary>
        internal static string r1 {
            get {
                return ResourceManager.GetString("r1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s no ordinary rabbit!.
        /// </summary>
        internal static string r1description {
            get {
                return ResourceManager.GetString("r1description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare.
        /// </summary>
        internal static string rare {
            get {
                return ResourceManager.GetString("rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s delve into the massive dungeon known as Morse Hall.
        /// </summary>
        internal static string room {
            get {
                return ResourceManager.GetString("room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A pit yawns open before you just on the other side of the door&apos;s threshold. The entire floor of the room has fallen into a second room beneath it. Across the way you can spy a door in the wall now 15 feet off the rubble-strewn floor, and near the center of the room stands a thick column of mortared stone that appears to hold the spiral staircase that leads down to what was the lower level..
        /// </summary>
        internal static string room10 {
            get {
                return ResourceManager.GetString("room10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A huge stewpot hangs from a thick iron tripod over a crackling fire in the center of this chamber. A hole in the ceiling allows some of the smoke from the fire to escape, but much of it expands across the ceiling and rolls down to fill the room in a dark fog. Other details are difficult to make out, but some creature must be nearby, because it smells like a good soup is cooking..
        /// </summary>
        internal static string room2 {
            get {
                return ResourceManager.GetString("room2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rats inside the room shriek when they hear the door open, then they run in all directions from a putrid corpse lying in the center of the floor. As these creatures crowd around the edges of the room, seeking to crawl through a hole in one corner, they fight one another. The stinking corpse in the middle of the room looks human, but the damage both time and the rats have wrought are enough to make determining its race by appearance an extremely difficult task at best..
        /// </summary>
        internal static string room3 {
            get {
                return ResourceManager.GetString("room3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This room is shattered. A huge crevasse shears the chamber in half, and the ground and ceilings are tilted away from it. It&apos;s as though the room was gripped in two enormous hands and broken like a loaf of bread. Someone has torn a tall stone door from its hinges somewhere else in the dungeon and used it to bridge the 15-foot gap of the chasm between the two sides of the room. Whatever did that must have possessed tremendous strength because the door is huge, and the enormous hinges look bent and mangled..
        /// </summary>
        internal static string room4 {
            get {
                return ResourceManager.GetString("room4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As soon as you entered the room, a dazzling white light blinds you. Just as you wondered if you finally got out of the dungoen, an eerie sound echoes from the distant, sharpening your mind. When your eyes finally adapted to the light, you looked around in alert and noticed something on the walls. Once you stood closer to it, you realized that the entire wall has the word &quot;death&quot; written all over it in some mysterious red liquid. The unsettling scene gave you goosebumps as you became even more determined abo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string room5 {
            get {
                return ResourceManager.GetString("room5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This small chamber seems divided into three parts. The first has several hooks on the walls from which hang dusty robes. An open curtain separates that space from the next, which has a dry basin set in the floor. Beyond that lies another parted curtain behind which you can see several straw mats in a semicircle pointing toward a statue of a dog-headed man..
        /// </summary>
        internal static string room6 {
            get {
                return ResourceManager.GetString("room6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The burble of water reaches your ears after you open the door to this room. You see the source of the noise in the far wall: a large fountain artfully carved to look like a seashell with the figure of a seacat spewing clear water into its basin..
        /// </summary>
        internal static string room7 {
            get {
                return ResourceManager.GetString("room7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A rusted portcullis stands just beyond the door. Looking into the room, you see three other exits, similarly blocked by portcullises. Four monsters dressed in aged clothing and rusting armor lie on the floor in the room against the walls. They seem in poses of repose rather than violence..
        /// </summary>
        internal static string room8 {
            get {
                return ResourceManager.GetString("room8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A flurry of bats suddenly flaps through the doorway, their screeching barely audible as they careen past your heads. They flap past you into the rooms and halls beyond. The room from which they came seems barren at first glance..
        /// </summary>
        internal static string room9 {
            get {
                return ResourceManager.GetString("room9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runnnnnn!!.
        /// </summary>
        internal static string run {
            get {
                return ResourceManager.GetString("run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected {0}!.
        /// </summary>
        internal static string selected {
            get {
                return ResourceManager.GetString("selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your player
        ///A) Viking
        ///B) Chief
        ///C) Deathwing
        ///D) Elf
        ///E) Caveman
        ///F) Orc
        ///G) Gnome
        ///H) Native
        ///I) Goblin
        ///J) Localization Professional.
        /// </summary>
        internal static string selectPlayer {
            get {
                return ResourceManager.GetString("selectPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string standard {
            get {
                return ResourceManager.GetString("standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =-=-DUNGEON OF DOOM!-=-=.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Count.
        /// </summary>
        internal static string v1 {
            get {
                return ResourceManager.GetString("v1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Vampire.
        /// </summary>
        internal static string v1description {
            get {
                return ResourceManager.GetString("v1description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a punishment of not choosing a valid option, you have automatically became a Goblin..
        /// </summary>
        internal static string validOption {
            get {
                return ResourceManager.GetString("validOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seafaring Viking.
        /// </summary>
        internal static string viking {
            get {
                return ResourceManager.GetString("viking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abyssal Whip.
        /// </summary>
        internal static string w1 {
            get {
                return ResourceManager.GetString("w1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rusted Knife.
        /// </summary>
        internal static string w2 {
            get {
                return ResourceManager.GetString("w2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Sword.
        /// </summary>
        internal static string w3 {
            get {
                return ResourceManager.GetString("w3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat Knife.
        /// </summary>
        internal static string w4 {
            get {
                return ResourceManager.GetString("w4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sword.
        /// </summary>
        internal static string w5 {
            get {
                return ResourceManager.GetString("w5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon Breath.
        /// </summary>
        internal static string w6 {
            get {
                return ResourceManager.GetString("w6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Power of C#.
        /// </summary>
        internal static string w7 {
            get {
                return ResourceManager.GetString("w7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to your journey!.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Flood of Zombies.
        /// </summary>
        internal static string z1 {
            get {
                return ResourceManager.GetString("z1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s ALIVE! THEY&apos;RE ALL ALIVE!!!.
        /// </summary>
        internal static string z1description {
            get {
                return ResourceManager.GetString("z1description", resourceCulture);
            }
        }
    }
}
